name: Build and Upload

on:
  push:
      branches:
          - asdfasdf
permissions:
    contents: write
  
jobs:
    shellcheck:
      uses: ./.github/workflows/shellcheck.yml
    shfmt:
      uses: ./.github/workflows/shfmt.yml
    repocheck:
      uses: ./.github/workflows/repocheck.yml
  
    build-and-push:
        # container:
        #   image: ubuntu:22.04
        #   options: --privileged
        runs-on: ubuntu-22.04
        needs: [shellcheck, shfmt, repocheck]
        if:  ${{ ! startsWith(github.event.head_commit.message, 'x') }}
        strategy:
            matrix:
                image: [
                        mirte_orangepi3b_ros2
                        ]
                type: [
                  default, mirte-master
                ]
            fail-fast: false
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Extract branch name
              shell: bash
              run: |
                echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
                echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_OUTPUT
              id: extract_branch
            - name: setup this repo
              run: |
                    sudo apt update
                    sudo apt install qemu-user-static parted -y
                    PACKER_GITHUB_API_TOKEN=${{ secrets.GITHUB_TOKEN }}
                    ./packerInstall.sh

            - name: setup build files
              run: |
                    echo -e "MIRTE_TYPE=${{ matrix.type }}" >> settings.sh
                    cat settings.sh
            # - name: setup repos
            #   run: |
            #     cp main_repos.yaml repos.yaml
            #     yq e -i '.repositories.mirte-ros-packages.version = "fix-intro-rob"' repos.yaml
            #     yq e -i '.repositories.mirte-telemetrix4arduino.url =  "https://github.com/arendjan/telemetrix4arduino.git"' repos.yaml
            #     yq e -i '.repositories.mirte-telemetrix4arduino.version = "fix-intro-robotics"' repos.yaml
            - name: Build
              run: |
                    ./packerBuild.sh ${{ matrix.image }}
            - name: artifacts
              uses: actions/upload-artifact@v4
              with:
                path: build/*.img.xz
                name: ${{ matrix.image }}-${{ matrix.type }}-${{ steps.extract_branch.outputs.branch }}
            - name: Push to release
              uses: softprops/action-gh-release@v2
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  files: build/*.img.xz
