name: Build and Upload


# build a single image, based on sbc and type inputs.
# uploads to artifacts and releases
# runs installer build if mirte-master
on:
  workflow_call:
    inputs:
      branch:
        required: false
        type: string
        default: main
  workflow_dispatch:

permissions:
    contents: write
  
jobs:
    build-and-push_overlay:
        # container:
        #   image: ubuntu:22.04
        #   options: --privileged
        runs-on: ubuntu-22.04
        
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                ref: ${{ inputs.branch }}
            - name: Create overlay image
              run: |
                sudo ./scripts/create_overlay.sh
            - name: artifacts
              uses: actions/upload-artifact@v4
              if: always()
              with:
                path: build/*.img.xz
                name: overlay_image
            - name: Push to release
              uses: softprops/action-gh-release@v2
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  files: build/*.img.xz
