on:
  # - push
  - pull_request
  - workflow_call

name: "reposcheck"
permissions: {}

jobs:
  reposcheck:
    name: reposcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install vcstool
        run: |
          sudo apt update
          sudo apt-get install python3-pip
          sudo pip install vcstool
          mkdir check
      - name: check (Main)
        if: ${{ ! startsWith(github.ref_name, 'develop') }}
        run: vcs import --shallow --input default_repos.yaml check
      - name: check (Develop)
        if: ${{ startsWith(github.ref_name, 'develop') }}
        run: vcs import --shallow --input develop_repos.yaml check

