on:
  # - push
  workflow_call:
    inputs:
      branch:
        required: false
        type: string
        default: main
  pull_request:

name: "Shellcheck"
permissions: {}

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
            severity: warning
