name: shfmt
on:
  workflow_call:
    inputs:
      branch:
        required: false
        type: string
        default: main
  pull_request:
  # - push
jobs:
  sh-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
      - name: Run the sh-checker
        uses: luizm/action-sh-checker@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          sh_checker_shellcheck_disable: true
          sh_checker_comment: true
